version: '3'

networks:
    laravel:
        
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - 8088:80
        volumes:
            - .:/var/www/html:delegated
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
            - redis
            - mailhog
        networks:
            - laravel
    
    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - 4306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: imessenger
            MYSQL_USER: imessenger
            MYSQL_PASSWORD: 4e7cfa
            MYSQL_ROOT_PASSWORD: 4e7cfa
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        restart: unless-stopped
        tty: true
        networks:
            - laravel
            
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        ports:
            - 9000:9000
        volumes:
            - .:/var/www/html:delegated
        networks:
            - laravel
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: 4e7cfa
        depends_on:
            - mysql
        restart: always
        networks:
            - laravel
            
    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        networks:
            - laravel
            
    npm:
        image: node:latest
        container_name: npm
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel
            
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - 6378:6379
        restart: unless-stopped
        networks:
            - laravel
            
    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: artisan
        volumes:
            - .:/var/www/html:delegated
        working_dir: /var/www/html
        entrypoint: ['/var/www/html/artisan']
        depends_on:
            - mysql
        networks:
            - laravel
            
    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - laravel
            